# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20170707_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredient',
            name='name',
            field=models.CharField(default='fixme', max_length=100),
            preserve_default=False,
        ),
    ]
