# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredient',
            name='name',
        ),
    ]
