# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0005_remove_meal_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(related_name='meal', through='meals.MealIngredient', to='meals.Ingredient'),
        ),
        migrations.AddField(
            model_name='meal',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
