# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20170707_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcals',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='amount_grams',
            field=models.FloatField(),
        ),
    ]
