# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_auto_20170707_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='kcals',
            new_name='kcal',
        ),
    ]
