# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20170707_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
