# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20170707_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
