# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_auto_20170707_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
