# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_auto_20170707_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
