# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_auto_20170721_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='kind',
        ),
    ]
